#!/bin/bash
# Post-Deployment Setup Script for BubblyBatch
# Run this after successful AWS backend deployment

set -e

echo "=== BubblyBatch Post-Deployment Setup ==="
echo ""

# Check if deployment outputs file exists
DEPLOY_LOG="/Users/remi.tuyaerts/Documents/Github/BubblyBatch/backend/deploy.log"

if [ ! -f "$DEPLOY_LOG" ]; then
  echo "⚠️  Deployment log not found. Please run backend deployment first:"
  echo "   cd backend && npm run deploy:dev"
  exit 1
fi

# Extract values from deployment output
echo "📋 Extracting deployment values..."
API_URL=$(grep -A 20 "Stack Outputs" "$DEPLOY_LOG" | grep "ApiUrl:" | awk '{print $2}' || echo "")
USER_POOL_ID=$(grep -A 20 "Stack Outputs" "$DEPLOY_LOG" | grep "UserPoolId:" | awk '{print $2}' || echo "")
CLIENT_ID=$(grep -A 20 "Stack Outputs" "$DEPLOY_LOG" | grep "UserPoolClientId:" | awk '{print $2}' || echo "")

if [ -z "$API_URL" ] || [ -z "$USER_POOL_ID" ] || [ -z "$CLIENT_ID" ]; then
  echo ""
  echo "⚠️  Could not extract values automatically."
  echo "Please manually enter the values from the deployment output:"
  echo ""
  read -p "API URL: " API_URL
  read -p "User Pool ID: " USER_POOL_ID
  read -p "User Pool Client ID: " CLIENT_ID
fi

echo ""
echo "✓ Using the following values:"
echo "  API URL: $API_URL"
echo "  User Pool ID: $USER_POOL_ID"
echo "  Client ID: $CLIENT_ID"
echo ""

# Create frontend .env file
echo "📝 Creating frontend .env file..."
cat > /Users/remi.tuyaerts/Documents/Github/BubblyBatch/frontend/.env << EOF
# BubblyBatch Frontend Environment Configuration
# Auto-generated by post-deployment-setup.sh

# API Configuration
EXPO_PUBLIC_USE_MOCK_API=false
EXPO_PUBLIC_USE_LOCAL_BACKEND=false
EXPO_PUBLIC_API_URL=$API_URL

# AWS Cognito Configuration
EXPO_PUBLIC_AWS_USER_POOL_ID=$USER_POOL_ID
EXPO_PUBLIC_AWS_USER_POOL_WEB_CLIENT_ID=$CLIENT_ID
EXPO_PUBLIC_AWS_REGION=us-east-1
EOF

echo "✓ Created frontend/.env"
echo ""

# Set EAS secrets
echo "🔐 Setting EAS secrets..."
cd /Users/remi.tuyaerts/Documents/Github/BubblyBatch/frontend

eas secret:create --name EXPO_PUBLIC_API_URL --value "$API_URL" --force || echo "  Note: Secret may already exist"
eas secret:create --name EXPO_PUBLIC_AWS_USER_POOL_ID --value "$USER_POOL_ID" --force || echo "  Note: Secret may already exist"
eas secret:create --name EXPO_PUBLIC_AWS_USER_POOL_WEB_CLIENT_ID --value "$CLIENT_ID" --force || echo "  Note: Secret may already exist"
eas secret:create --name EXPO_PUBLIC_AWS_REGION --value "us-east-1" --force || echo "  Note: Secret may already exist"
eas secret:create --name EXPO_PUBLIC_USE_MOCK_API --value "false" --force || echo "  Note: Secret may already exist"
eas secret:create --name EXPO_PUBLIC_USE_LOCAL_BACKEND --value "false" --force || echo "  Note: Secret may already exist"

echo ""
echo "✓ EAS secrets configured"
echo ""

# Create test user
echo "👤 Creating test user in Cognito..."
read -p "Enter test email address (default: test@bubblebatch.com): " TEST_EMAIL
TEST_EMAIL=${TEST_EMAIL:-test@bubblebatch.com}
TEST_PASSWORD="TempPassword123!"

echo "  Creating user: $TEST_EMAIL"
aws cognito-idp sign-up \
  --client-id "$CLIENT_ID" \
  --username "$TEST_EMAIL" \
  --password "$TEST_PASSWORD" \
  --user-attributes Name=email,Value="$TEST_EMAIL" 2>/dev/null || echo "  User may already exist"

echo "  Confirming user (admin)..."
aws cognito-idp admin-confirm-sign-up \
  --user-pool-id "$USER_POOL_ID" \
  --username "$TEST_EMAIL" 2>/dev/null || echo "  User may already be confirmed"

echo ""
echo "✓ Test user created: $TEST_EMAIL / $TEST_PASSWORD"
echo ""

# Save credentials to file
cat > /Users/remi.tuyaerts/Documents/Github/BubblyBatch/TEST_CREDENTIALS.txt << EOF
BubblyBatch Test Credentials
============================

API URL: $API_URL
User Pool ID: $USER_POOL_ID
Client ID: $CLIENT_ID

Test User:
  Email: $TEST_EMAIL
  Password: $TEST_PASSWORD

To test the API:
  1. Get auth token:
     aws cognito-idp initiate-auth \\
       --auth-flow USER_PASSWORD_AUTH \\
       --client-id $CLIENT_ID \\
       --auth-parameters USERNAME=$TEST_EMAIL,PASSWORD=$TEST_PASSWORD
  
  2. Use the IdToken in API requests:
     curl -H "Authorization: Bearer YOUR_ID_TOKEN" \\
       $API_URL/batches

Next Steps:
  1. Build mobile app: cd frontend && eas build --platform all --profile preview
  2. Install on device using QR code
  3. Login with test credentials
EOF

echo "✓ Saved credentials to TEST_CREDENTIALS.txt"
echo ""
echo "=== Setup Complete! ==="
echo ""
echo "Next steps:"
echo "  1. Build the mobile app:"
echo "     cd frontend"
echo "     eas build --platform all --profile preview"
echo ""
echo "  2. Install on your device using the QR code"
echo "  3. Login with: $TEST_EMAIL / $TEST_PASSWORD"
echo ""

